[meta]
name = "EnzymeML"
description = "This is a code and schema generator for Strenda Biocatalysis."
paths = ["specifications/v2.md"]

[generate]
xml-schema = { out = "schemes/v2/enzymeml-v2.xsd" }
shacl = { out = "schemes/v2/enzymeml-v2.ttl" }
shex = { out = "schemes/v2/enzymeml-v2.shex" }
protobuf = { out = "schemes/v2/enzymeml-v2.proto" }
graphql = { out = "schemes/v2/enzymeml-v2.graphql" }
json-schema = { out = "schemes/v2/enzymeml-v2.json", root = "EnzymeMLDocument" }
python-pydantic-xml = { out = "pyenzyme/v2.py" }
mk-docs = { out = "docs/versions/v2.md", nav = "true" }
typescript-zod = { out = "enzymeml-ts/src/index.ts" }
rust = { out = "enzymeml-rs/src/versions/v2.rs" }
golang = { out = "enzymeml-go/src/v2.go" }
