[meta]
name = "EnzymeML"
description = "This is a code and schema generator for EnzymeML."
paths = ["specifications/v2.md"]

[generate]
xml-schema = { out = "schemes/*/enzymeml-*.xsd", per-spec = true }
shacl = { out = "schemes/*/enzymeml-*.ttl", per-spec = true }
shex = { out = "schemes/*/enzymeml-*.shex", per-spec = true }
protobuf = { out = "schemes/*/enzymeml-*.proto", per-spec = true }
graphql = { out = "schemes/*/enzymeml-*.graphql", per-spec = true }
linkml = { out = "schemes/*/enzymeml-*-linkml.yaml", per-spec = true }
json-schema = { out = "schemes/*/enzymeml-*.json", root = "EnzymeMLDocument", per-spec = true }
mk-docs = { out = "docs/versions/*.md", nav = "true", per-spec = true }
golang = { out = "enzymeml-go/src/*.go", per-spec = true, gorm = "true" }
typescript-zod = { out = "enzymeml-ts/src/*.ts", per-spec = true }
julia = { out = "enzymeml-jl/src/*.jl", per-spec = true, fname-case = "Pascal" }
mermaid = { out = "diagrams/*.md", per-spec = true }

# These libraries have their own repositories and are not part of this one
# rust = { out = "enzymeml-rs/src/versions/*.rs", per-spec = true }
# python-pydantic = { out = "enzymeml-py/models/*.py", per-spec = true, astropy = true }
