import sdRDM

from typing import List, Optional
from pydantic import PrivateAttr, validator
from uuid import uuid4
from pydantic_xml import attr, element, wrapped
from sdRDM.base.listplus import ListPlus
from sdRDM.base.utils import forge_signature
from .datatypes import DataTypes
from .replicate import Replicate
from .abstractspecies import AbstractSpecies


@forge_signature
class MeasurementData(
    sdRDM.DataModel,
    nsmap={
        "": "https://github.com/EnzymeML/enzymeml-specifications@142ca246cf92944bcbc11fbda9892f64bff77e8b#MeasurementData"
    },
):
    """This object describes a single entity of a measurement, which corresponds to one species. It also holds replicates that contain time course data."""

    id: Optional[str] = attr(
        name="id",
        description="Unique identifier of the given object.",
        default_factory=lambda: str(uuid4()),
        xml="@id",
    )

    init_conc: float = element(
        description="Initial concentration of the measurement data.",
        tag="init_conc",
        json_schema_extra=dict(),
    )

    unit: str = element(
        description="The unit of measurement data.",
        tag="unit",
        json_schema_extra=dict(),
    )

    measurement_id: str = element(
        description="Unique measurement identifier this dataset belongs to.",
        tag="measurement_id",
        json_schema_extra=dict(),
    )

    species_id: Optional[str] = element(
        description="The identifier for the described reactant.",
        default=None,
        tag="species_id",
        json_schema_extra=dict(),
    )

    replicates: List[Replicate] = wrapped(
        "replicates",
        element(
            description=(
                "A list of replicate objects holding raw data of the measurement."
            ),
            default_factory=ListPlus,
            tag="Replicate",
            json_schema_extra=dict(multiple=True),
        ),
    )
    _repo: Optional[str] = PrivateAttr(
        default="https://github.com/EnzymeML/enzymeml-specifications"
    )
    _commit: Optional[str] = PrivateAttr(
        default="142ca246cf92944bcbc11fbda9892f64bff77e8b"
    )

    def add_to_replicates(
        self,
        species_id: AbstractSpecies,
        measurement_id: str,
        data_unit: str,
        time_unit: str,
        data_type: DataTypes = DataTypes.CONCENTRATION,
        time: List[float] = ListPlus(),
        data: List[float] = ListPlus(),
        is_calculated: bool = False,
        uri: Optional[str] = None,
        creator_id: Optional[str] = None,
        id: Optional[str] = None,
    ) -> Replicate:
        """
        This method adds an object of type 'Replicate' to attribute replicates

        Args:
            id (str): Unique identifier of the 'Replicate' object. Defaults to 'None'.
            species_id (): Unique identifier of the species that has been measured..
            measurement_id (): Unique identifier of the measurement that the replicate is part of..
            data_unit (): SI unit of the data that was measured..
            time_unit (): Time unit of the replicate..
            data_type (): Type of data that was measured (e.g. concentration). Defaults to DataTypes.CONCENTRATION
            time (): Time steps of the replicate.. Defaults to ListPlus()
            data (): Data that was measured.. Defaults to ListPlus()
            is_calculated (): Whether or not the data has been generated by simulation.. Defaults to False
            uri (): URI of the protein.. Defaults to None
            creator_id (): Unique identifier of the author.. Defaults to None
        """
        params = {
            "species_id": species_id,
            "measurement_id": measurement_id,
            "data_unit": data_unit,
            "time_unit": time_unit,
            "data_type": data_type,
            "time": time,
            "data": data,
            "is_calculated": is_calculated,
            "uri": uri,
            "creator_id": creator_id,
        }
        if id is not None:
            params["id"] = id
        self.replicates.append(Replicate(**params))
        return self.replicates[-1]

    @validator("species_id")
    def get_species_id_reference(cls, value):
        """Extracts the ID from a given object to create a reference"""
        from .abstractspecies import AbstractSpecies

        if isinstance(value, AbstractSpecies):
            return value.id
        elif isinstance(value, str):
            return value
        elif value is None:
            return value
        else:
            raise TypeError(
                f"Expected types [AbstractSpecies, str] got '{type(value).__name__}'"
                " instead."
            )

    @validator("species_id")
    def get_species_id_reference(cls, value):
        """Extracts the ID from a given object to create a reference"""
        from .abstractspecies import AbstractSpecies

        if isinstance(value, AbstractSpecies):
            return value.id
        elif isinstance(value, str):
            return value
        elif value is None:
            return value
        else:
            raise TypeError(
                f"Expected types [AbstractSpecies, str] got '{type(value).__name__}'"
                " instead."
            )

    @validator("species_id")
    def get_species_id_reference(cls, value):
        """Extracts the ID from a given object to create a reference"""

        from .abstractspecies import AbstractSpecies

        if isinstance(value, AbstractSpecies):
            return value.id
        elif isinstance(value, str):
            return value
        elif value is None:
            return value
        else:
            raise TypeError(
                f"Expected types [AbstractSpecies, str] got '{type(value).__name__}'"
                " instead."
            )
