# This file contains Julia type definitions with JSON serialization.
#
# WARNING: This is an auto-generated file.
# Do not edit directly - any changes will be overwritten.

module EnzymemlV2

using JSON3
using StructTypes

#=
  Type Definitions
  ---------------
  Main struct definitions with their fields and JSON serialization support.
=#
"""
Represents a base unit in the unit definition.
"""
Base.@kwdef mutable struct BaseUnit
    """
    Kind of the base unit (e.g., meter, kilogram, second).
    """
    kind::String

    """
    Exponent of the base unit in the unit definition.
    """
    exponent::Int64

    """
    Multiplier of the base unit in the unit definition.
    """
    multiplier::Union{Float64, Nothing} = nothing

    """
    Scale of the base unit in the unit definition.
    """
    scale::Union{Float64, Nothing} = nothing

end

export BaseUnit

"""
Represents a unit definition that is based on the SI unit system.
"""
Base.@kwdef mutable struct UnitDefinition
    """
    Unique identifier of the unit definition.
    """
    id::Union{String, Nothing} = nothing

    """
    Common name of the unit definition.
    """
    name::Union{String, Nothing} = nothing

    """
    Base units that define the unit.
    """
    base_units::Union{Vector{
    BaseUnit}, Nothing} = nothing

end

export UnitDefinition

"""
This object describes a single entity of a measurement, which
corresponds to one species. It also holds replicates that contain time
course data.
"""
Base.@kwdef mutable struct MeasurementData
    """
    The identifier for the described reactant.
    """
    species_id::String

    """
    Initial amount of the measurement data. This must be the same as the
    first data point in the array.
    """
    initial::Float64

    """
    SI unit of the data that was measured.
    """
    data_unit::
    UnitDefinition

    """
    Type of data that was measured (e.g. concentration)
    """
    data_type::String

    """
    Amount of the reactant before the measurement. This field should
    be used for specifying the prepared amount of a species in
    the reaction mix. Not to be confused with , specifying the
    concentration at the first data point from the array.
    """
    prepared::Union{Float64, Nothing} = nothing

    """
    Data that was measured.
    """
    data::Union{Vector{Float64}, Nothing} = nothing

    """
    Time steps of the replicate.
    """
    time::Union{Vector{Float64}, Nothing} = nothing

    """
    Time unit of the replicate.
    """
    time_unit::Union{
    UnitDefinition, Nothing} = nothing

    """
    Whether or not the data has been generated by simulation.
    """
    is_simulated::Bool

end

export MeasurementData

"""
This object describes the result of a measurement, which includes
time course data of any type defined in DataTypes. It includes initial
concentrations of all species used in a single measurement.
"""
Base.@kwdef mutable struct Measurement
    """
    Unique identifier of the measurement.
    """
    id::String

    """
    Name of the measurement
    """
    name::String

    """
    Measurement data of all species that were part of the measurement. A
    species can refer to a protein, complex, or small molecule.
    """
    species_data::Union{Vector{
    MeasurementData}, Nothing} = nothing

    """
    User-defined group ID to signal relationships between measurements.
    """
    group_id::Union{String, Nothing} = nothing

    """
    PH value of the measurement.
    """
    ph::Union{Float64, Nothing} = nothing

    """
    Temperature of the measurement.
    """
    temperature::Union{Float64, Nothing} = nothing

    """
    Unit of the temperature of the measurement.
    """
    temperature_unit::Union{
    UnitDefinition, Nothing} = nothing

end

export Measurement

"""
This object describes the parameters of the kinetic model and can
include all estimated values.
"""
Base.@kwdef mutable struct Parameter
    """
    Unique identifier of the parameter.
    """
    id::String

    """
    Name of the parameter.
    """
    name::String

    """
    Symbol of the parameter.
    """
    symbol::String

    """
    Numerical value of the estimated parameter.
    """
    value::Union{Float64, Nothing} = nothing

    """
    Unit of the estimated parameter.
    """
    unit::Union{
    UnitDefinition, Nothing} = nothing

    """
    Initial value that was used for the parameter estimation.
    """
    initial_value::Union{Float64, Nothing} = nothing

    """
    Upper bound of the estimated parameter.
    """
    upper_bound::Union{Float64, Nothing} = nothing

    """
    Lower bound of the estimated parameter.
    """
    lower_bound::Union{Float64, Nothing} = nothing

    """
    Standard error of the estimated parameter.
    """
    stderr::Union{Float64, Nothing} = nothing

    """
    Specifies if this parameter is constant
    """
    constant::Union{Bool, Nothing} = nothing

end

export Parameter

"""
This object describes a variable that is part of an equation.
"""
Base.@kwdef mutable struct Variable
    """
    Unique identifier of the variable.
    """
    id::String

    """
    Name of the variable.
    """
    name::String

    """
    Symbol of the variable.
    """
    symbol::String

end

export Variable

"""
This object describes an equation that can be used to model the
kinetics of a reaction. There are different types of equations that
can be used to model the kinetics of a reaction. The equation can be
an ordinary differential equation, a rate law or assignment rule.
"""
Base.@kwdef mutable struct Equation
    """
    Internal identifier to a species defined in the EnzymeMLDocument,
    given it is a rate equation.
    """
    species_id::String

    """
    Mathematical expression of the equation.
    """
    equation::String

    """
    Type of the equation.
    """
    equation_type::String

    """
    List of variables that are part of the equation
    """
    variables::Union{Vector{
    Variable}, Nothing} = nothing

end

export Equation

"""
This object is part of the Reaction object and describes either an
educt, product or modifier. The latter includes buffers, counter-ions
as well as proteins/enzymes.
"""
Base.@kwdef mutable struct ReactionElement
    """
    Internal identifier to either a protein or reactant defined in the
    EnzymeMLDocument.
    """
    species_id::String

    """
    Float number representing the associated stoichiometry.
    """
    stoichiometry::Float64

end

export ReactionElement

"""
This object describes a chemical or enzymatic reaction that was
investigated in the course of the experiment. All species used within
this object need to be part of the data model.
"""
Base.@kwdef mutable struct Reaction
    """
    Unique identifier of the reaction.
    """
    id::String

    """
    Name of the reaction.
    """
    name::String

    """
    Whether the reaction is reversible or irreversible
    """
    reversible::Bool

    """
    Mathematical expression of the reaction.
    """
    kinetic_law::Union{
    Equation, Nothing} = nothing

    """
    List of reaction elements that are part of the reaction.
    """
    species::Union{Vector{
    ReactionElement}, Nothing} = nothing

    """
    List of reaction elements that are not part of the reaction but
    influence it.
    """
    modifiers::Union{Vector{String}, Nothing} = nothing

end

export Reaction

"""
This object describes the reactants that were used or produced in the
course of the experiment.
"""
Base.@kwdef mutable struct SmallMolecule
    """
    Unique identifier of the small molecule.
    """
    id::String

    name::String

    constant::Bool

    """
    Unique identifier of the vessel this small molecule has been used in.
    """
    vessel_id::Union{String, Nothing} = nothing

    """
    Canonical Simplified Molecular-Input Line-Entry System (SMILES)
    encoding of the reactant.
    """
    canonical_smiles::Union{String, Nothing} = nothing

    """
    International Chemical Identifier (InChI) encoding of the reactant.
    """
    inchi::Union{String, Nothing} = nothing

    """
    Hashed International Chemical Identifier (InChIKey) encoding of the
    reactant.
    """
    inchikey::Union{String, Nothing} = nothing

    """
    Array of references to publications, database entries, etc. that
    describe the reactant.
    """
    references::Union{Vector{String}, Nothing} = nothing

end

export SmallMolecule

"""
This object describes complexes made of reactants and/or proteins that
were used or produced in the course of the experiment.
"""
Base.@kwdef mutable struct Complex
    """
    Unique identifier of the complex.
    """
    id::String

    name::String

    constant::Bool

    """
    Unique identifier of the vessel this complex has been used in.
    """
    vessel_id::Union{String, Nothing} = nothing

    """
    Array of IDs the complex contains
    """
    participants::Union{Vector{String}, Nothing} = nothing

end

export Complex

"""
This object describes the proteins that were used or formed throughout
the experiment.
"""
Base.@kwdef mutable struct Protein
    """
    Unique internal identifier of the protein.
    """
    id::String

    name::String

    constant::Bool

    """
    Amino acid sequence of the protein
    """
    sequence::Union{String, Nothing} = nothing

    """
    Unique identifier of the vessel this protein has been used in.
    """
    vessel_id::Union{String, Nothing} = nothing

    """
    EC number of the protein.
    """
    ecnumber::Union{String, Nothing} = nothing

    """
    Organism the protein was expressed in.
    """
    organism::Union{String, Nothing} = nothing

    """
    Taxonomy identifier of the expression host.
    """
    organism_tax_id::Union{String, Nothing} = nothing

    """
    Array of references to publications, database entries, etc. that
    describe the protein.
    """
    references::Union{Vector{String}, Nothing} = nothing

end

export Protein

"""
This object describes vessels in which the experiment has been
carried out. These can include any type of vessel used in biocatalytic
experiments.
"""
Base.@kwdef mutable struct Vessel
    """
    Unique identifier of the vessel.
    """
    id::String

    """
    Name of the used vessel.
    """
    name::String

    """
    Volumetric value of the vessel.
    """
    volume::Float64

    """
    Volumetric unit of the vessel.
    """
    unit::
    UnitDefinition

    """
    Whether the volume of the vessel is constant or not.
    """
    constant::Bool

end

export Vessel

"""
The creator object contains all information about authors that
contributed to the resulting document.
"""
Base.@kwdef mutable struct Creator
    """
    Given name of the author or contributor.
    """
    given_name::String

    """
    Family name of the author or contributor.
    """
    family_name::String

    """
    Email address of the author or contributor.
    """
    mail::String

end

export Creator

"""
This is the root object that composes all objects found in an
EnzymeML document. It also includes general metadata such as the
name of the document, when it was created/modified, and references to
publications, databases, and arbitrary links to the web.
"""
Base.@kwdef mutable struct EnzymeMLDocument
    """
    Title of the EnzymeML Document.
    """
    name::String

    """
    Contains references to publications, databases, and arbitrary links to
    the web.
    """
    references::Union{Vector{String}, Nothing} = nothing

    """
    Date the EnzymeML document was created.
    """
    created::Union{String, Nothing} = nothing

    """
    Date the EnzymeML document was modified.
    """
    modified::Union{String, Nothing} = nothing

    """
    Contains all authors that are part of the experiment.
    """
    creators::Union{Vector{
    Creator}, Nothing} = nothing

    """
    Contains all vessels that are part of the experiment.
    """
    vessels::Union{Vector{
    Vessel}, Nothing} = nothing

    """
    Contains all proteins that are part of the experiment.
    """
    proteins::Union{Vector{
    Protein}, Nothing} = nothing

    """
    Contains all complexes that are part of the experiment.
    """
    complexes::Union{Vector{
    Complex}, Nothing} = nothing

    """
    Contains all reactants that are part of the experiment.
    """
    small_molecules::Union{Vector{
    SmallMolecule}, Nothing} = nothing

    """
    Dictionary mapping from reaction IDs to reaction-describing objects.
    """
    reactions::Union{Vector{
    Reaction}, Nothing} = nothing

    """
    Contains measurements that describe outcomes of an experiment.
    """
    measurements::Union{Vector{
    Measurement}, Nothing} = nothing

    """
    Contains ordinary differential equations that describe the kinetic
    model.
    """
    equations::Union{Vector{
    Equation}, Nothing} = nothing

    """
    List of parameters that are part of the equation
    """
    parameters::Union{Vector{
    Parameter}, Nothing} = nothing

end

export EnzymeMLDocument


end # module enzymeml_v2