name: MD-Models Pipeline

on:
  workflow_dispatch:
    inputs:
      run-gen:
        description: 'Run the generation pipeline'
        required: true
        default: 'true'

jobs:
  generate:
    name: Generate Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        if: inputs.run-gen == 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install MD-Models
        if: inputs.run-gen == 'true'
        run: cargo install --git https://github.com/JR-1991/md-models.git

      - name: Run the generation pipeline
        if: inputs.run-gen == 'true'
        run: md-models pipeline -i gen.toml

      - name: Format the generated code
        if: inputs.run-gen == 'true'
        uses: chartboost/ruff-action@v1
        with:
          args: 'format'

      - name: 'Push generated code/schemes'
        if: inputs.run-gen == 'true'
        shell: 'bash'
        run: |
          if [[ `git status --porcelain` ]]; then
              git add --all
              git config --global user.name 'MD-Models Bot'
              git config --global user.email 'mdmodels@bot.com'
              git commit -am "Model update"
              git push
          else
            echo "Nothing changed!"
          fi

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        with:
          path: .cache
          key: ${{ github.ref }}
      - run: pip install mkdocs-material jupyter nbconvert mkdocs-jupyter mkdocs-plugin-inline-svg
      - run: mkdocs build
      - run: echo 'enzymeml.org' > site/CNAME
      - run: mkdocs gh-deploy --force
