name: MD-Models Pipeline

on:
  workflow_dispatch:

jobs:
  generate:
    name: Generate Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          path: .cache
          key: ${{ github.ref }}
      - run: pip install mkdocs-material jupyter nbconvert mkdocs-jupyter mkdocs-plugin-inline-svg
      - run: mkdocs gh-deploy --force
