name: Generate ER Diagram

on: [push]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate sdRDM library
      uses: JR-1991/generate-sdrdm-api@v1
      with:
        library_name: "PyEnzyme"
        schema_path: "./specifications/enzymeml.md"
        schema: "true"
